name: Other CI with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
  multienv:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        node: [4, 6, 8, 10]
        exclude:
          # excludes node 4 on macOS
          - os: macos-latest
            node: 4
      # The maximum number of jobs that can run simultaneously when using a matrix job strategy. 
      max-parallel: 2
    runs-on: ${{ matrix.os }}
      steps:
        - id: step1
          run: echo "::set-output name=test::hello"
        - id: step2
          run: echo "::set-output name=test::world"
  